### ISSUE TITLE
K 1.19.x image?

### ISSUE THREAD

**Issue by texanraj** [kbst/kind-eks-d#4]
Do you guys have an image for K 1.19.x?

**Comment by ederst** [comment]
Doesn't look like it. But I assume it it possible to:
1) Fork the repo
2) [Bump the version in the Makefile and run make][1]
  * Optional: Change the `IMAGE_NAME` to a personal repo of yours so that you can push the image right away
3) Change the image name in the kubestack config (`config.auto.tfvars`) accordingly:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2979051/112283659-aa90f680-8c88-11eb-917b-f6f5ca2ecc01.png">

I will try that right away.

Since there are two versions of EKS-D right now ([will probably change to 3 with April 2021][2]), it might be a good idea to provide release branches for the Kind Docker Images of the different versions here (for example: `release-1.18`, `release-1.19`, etc.), but IDK if this is a priority of @pst, so this might be something one has to do themselves in a fork. ;)

[1]: https://github.com/kbst/kind-eks-d/blob/master/README.md
[2]: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by pst** [comment]
Feel free to send a PR that builds a newer EKS-D release and I am happy to cut a release. The current release is built from a prerelease of the EKS-D distribution archive that had a weird bug where everything was prefixed with `kubernetes`. That's what that weird rename loop in the Makefile is for. Probably won't be necessary for newer EKS-D releases anymore.

**Comment by ederst** [comment]
@texanraj so if you still want/need a 1.19.x image, i got https://github.com/kbst/kind-eks-d/pull/6 prepared. As of now, building the image only works with the master version of `kind` (`git clone <git url of kind>` and `make install INSTALL_DIR=/some/dir/on/the/PATH` and `make build-image`) and not on GH actions (see comment in PR).

So until `kind` does not get a new release this will remain broken for the automation here.
